#!/usr/bin/env bash
# ============================================================================
# OpenClaw — Secure Docker Setup (your repo)
# ============================================================================
# Run from this repo. Build the OpenClaw image from the main OpenClaw repo first:
#   cd /path/to/openclaw && docker build -t openclaw:local .
# ============================================================================
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

# Prerequisites
require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    err "Missing required tool: $1"
    exit 1
  fi
}
require_cmd docker
if ! docker compose version >/dev/null 2>&1; then
  err "Docker Compose v2 required. Try: docker compose version"
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  err "Docker daemon not running. Start Docker Desktop."
  exit 1
fi
ok "Docker and Docker Compose OK."

# Optional: build image from OpenClaw repo
OPENCLAW_REPO="${OPENCLAW_REPO:-}"
if [[ -n "$OPENCLAW_REPO" && -d "$OPENCLAW_REPO" ]]; then
  info "Building image from OpenClaw repo: $OPENCLAW_REPO"
  docker build -t openclaw:local -f "$OPENCLAW_REPO/Dockerfile" "$OPENCLAW_REPO"
  ok "Image openclaw:local built."
else
  warn "OPENCLAW_REPO not set or not a directory. Skipping image build."
  warn "Build from the OpenClaw repo first: cd path/to/openclaw && docker build -t openclaw:local ."
  if ! docker image inspect openclaw:local >/dev/null 2>&1; then
    err "Image openclaw:local not found. Set OPENCLAW_REPO or build manually."
    exit 1
  fi
  ok "Using existing openclaw:local image."
fi

# Directories
OPENCLAW_CONFIG_DIR="${OPENCLAW_CONFIG_DIR:-$HOME/.openclaw}"
OPENCLAW_WORKSPACE_DIR="${OPENCLAW_WORKSPACE_DIR:-$HOME/.openclaw/workspace}"
mkdir -p "$OPENCLAW_CONFIG_DIR" "$OPENCLAW_WORKSPACE_DIR" "$OPENCLAW_CONFIG_DIR/credentials"
chmod 700 "$OPENCLAW_CONFIG_DIR" "$OPENCLAW_WORKSPACE_DIR" "$OPENCLAW_CONFIG_DIR/credentials"
ok "Directories created."

# Token
if [[ -z "${OPENCLAW_GATEWAY_TOKEN:-}" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    OPENCLAW_GATEWAY_TOKEN="$(openssl rand -hex 32)"
  else
    err "Set OPENCLAW_GATEWAY_TOKEN or install openssl"
    exit 1
  fi
  ok "Gateway token generated."
fi

# .env
ENV_FILE="$ROOT_DIR/.env"
if [[ -f "$ENV_FILE" ]]; then
  cp "$ENV_FILE" "${ENV_FILE}.bak.$(date +%s)"
  warn "Existing .env backed up."
fi
cat > "$ENV_FILE" <<EOF
# Generated by secure-setup.sh
OPENCLAW_IMAGE=openclaw:local
OPENCLAW_CONFIG_DIR=${OPENCLAW_CONFIG_DIR}
OPENCLAW_WORKSPACE_DIR=${OPENCLAW_WORKSPACE_DIR}
OPENCLAW_GATEWAY_PORT=18789
OPENCLAW_BRIDGE_PORT=18790
OPENCLAW_GATEWAY_BIND=lan
OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}
EOF
chmod 600 "$ENV_FILE"
ok ".env written."

# Config
SECURE_CONFIG="$ROOT_DIR/openclaw.secure.json"
TARGET_CONFIG="$OPENCLAW_CONFIG_DIR/openclaw.json"
if [[ -f "$TARGET_CONFIG" ]]; then
  warn "Existing openclaw.json kept. To replace: cp $SECURE_CONFIG $TARGET_CONFIG"
else
  cp "$SECURE_CONFIG" "$TARGET_CONFIG"
  chmod 600 "$TARGET_CONFIG"
  ok "openclaw.secure.json copied to $TARGET_CONFIG"
fi

# Onboarding
info "Running onboarding..."
docker compose -f "$ROOT_DIR/docker-compose.secure.yml" run --rm openclaw-cli onboard --no-install-daemon

# Start
info "Starting gateway..."
docker compose -f "$ROOT_DIR/docker-compose.secure.yml" up -d openclaw-gateway

ok "OpenClaw gateway is running."
echo "  Dashboard: http://127.0.0.1:18789/"
echo "  Token: $OPENCLAW_GATEWAY_TOKEN"
